services:
  geosensors:
    image: "${IMAGE}:${TAG}"
    build:
      context: .
      dockerfile: Dockerfile

    # Подхват переменных из .env
    env_file:
      - .env

    # Внешний порт вынесен в HOST_PORT (по умолчанию 18080)
    ports:
      - "${HOST_PORT:-18080}:8080"

    restart: unless-stopped

